version: '3.7'
services:
  rabbitmq:
    image: rabbitmq:3.12.12-management
    container_name: rabbitmq
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_log:/var/log/rabbitmq/
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "youngchat123!!"
      RABBITMQ_LOGS: "/var/log/rabbitmq/rabbit.log"
  web:
    container_name: youngchat
    image: yongcowhee/youngchat-repo
    ports:
      - '8080:8080'
volumes:
  rabbitmq_data:
  rabbitmq_log: