name: CD

on:
# develop 브랜치로 push 되면 동작
  push:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout
    - name: Checkout
      uses: actions/checkout@v3

    # JDK version 설정
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    # AWS 자격 증명
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secret.AWS_IAM }}
        aws-region: ap-northeast-2

    # Amazon ECR 로그인
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
      
    # 도커 이미지 빌드 및 ECR에 푸시
    - name: Build Docker Image and Push to Amazon ECR
      env: 
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: ${{ secrets.ECR_REPO }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        sudo docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
        sudo docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
